### ISSUE TITLE
Running pocketsphinx with python compiler

### ISSUE THREAD

**Issue by Python-retropie-raspberry-pi-hobby** [cmusphinx/pocketsphinx#229] opened 2020-11-26 15:11 UTC
I'm am trying to create my own voice assistant. Pocketsphinx works great but it is a little slow on  a raspberrypi3b+. I'm am attempting to run pocketsphinx with the pypy3 python compiler. Here is the code I'm using:

[speack.txt](https://github.com/cmusphinx/pocketsphinx/files/5603721/speack.txt)
 This compiler does not import python3 modules in the regular sense. For third party modules you have to direct it to which folder to import from(as done with "tts" which is a module that allows it to speak to me) My question is: In what directory can I find "LIvespeech" and " get_model_path" ? The only reason I'm asking this is to be able to import it in  a compiler. Please help.

**Comment by dhdaines** [comment] 2022-07-22 12:02
Hi! Ideally we would rewrite the Python bindings with [CFFI](https://cffi.readthedocs.io/en/latest/) in order to give good performance and be compatible with PyPy, but that's more work than I want to put into an obsolete library like PocketSphinx.  However I am going to switch to Cython rather than SWIG, which is supported by PyPy, at least in theory, maybe today (see #256)

The slowness however will not be fixed by this since the actual ASR code is written in C rather than Python :)

**Comment by dhdaines** [comment] 2022-07-23 02:02
Confirmed working under PyPy 7.3.9-final (Python 3.8.13) as installed from conda-forge.

**Closed by dhdaines** 2022-07-23 02:02 UTC
